In [9]:
import pandas as pd
from tqdm import tqdm

In [2]:
df = pd.read_csv("Files/gitapress_v3_sn_hi_uvach_removed.csv")

df.head()

,sa,hi
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...
1,ताभ्यः पुरुषमानयत्ता अब्रुवन् सुकृतं वतेति पुर...,वह उनके लिये पुरुष ले आया वे बोले'यह सुन्दर बन...
2,इति श्रीमहाभारते शान्तिपर्वणि आपद्धर्मपर्वणि ल...,इस प्रकार श्रीमहाभारत शान्तिपर्वके अन्तर्गत आप...
3,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...
4,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...

# Skrutable Meter

In [3]:
import skrutable.utils as _utils
_utils._DEBUG_TIMING = True

from skrutable.meter_identification import MeterIdentifier, flush_profiling_report

MI = MeterIdentifier()
# for verse in my_verses:
#     MI.identify_meter(verse, resplit_option="resplit_lite", resplit_keep_midpoint=True, from_scheme="IAST")  # e.g.

# flush_profiling_report()

In [14]:
verse = df.loc[0, 'sa']
verse

'ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानमतयो वचसां प्रवाहैः नाराधितुं पुरुगुणैरधुनापि पित्रः किं तोष्टुमर्हति स मे हरिरुग्रजातेः ॥'

In [15]:
meter_info = MI.identify_meter(verse, resplit_option="resplit_lite", resplit_keep_midpoint=True, from_scheme="DEV")

In [16]:
meter_info.meter_label

'vasantatilakā [14: tBjjgg]'

In [24]:
print(meter_info.text_syllabified.split())

['bra', 'hmA', 'da', 'yaH', 'su', 'ra', 'ga', 'RA', 'mu', 'na', 'yo', "'Ta", 'si', 'dDAH', 'sa', 'ttvE', 'ka', 'tA', 'na', 'ma', 'ta', 'yo', 'va', 'ca', 'sAM', 'pra', 'vA', 'hEH', 'nA', 'rA', 'Di', 'tuM', 'pu', 'ru', 'gu', 'RE', 'ra', 'Du', 'nA', 'pi', 'pi', 'traH', 'kiM', 'to', 'zwu', 'ma', 'rha', 'ti', 'sa', 'me', 'ha', 'ri', 'ru', 'gra', 'jA', 'teH']

In [10]:
df['skr_out'] = ""


for i, r in tqdm(df.iterrows(), total=df.shape[0]):
    verse = df.loc[i, 'sa']
    meter_info = MI.identify_meter(verse, resplit_option="resplit_lite", resplit_keep_midpoint=True, from_scheme="DEV")
    df.loc[i, 'skr_out'] = meter_info.meter_label

100%|██████████| 74941/74941 [21:27<00:00, 58.21it/s]

In [13]:
df['skr_out'].unique()

array(['vasantatilakā [14: tBjjgg]',
       'upagīti (ardha 2: adhikamātrā, 27→28)',
       'āryā (ardha 1: ūnamātrā, 30→28; ardha 2: ūnamātrā, 27→26)', ...,
       'upajāti triṣṭubh: rathoddhatā 1; upendravajrā 2; svāgatā 3; ajñātam 4 (pāda 1 adhikākṣarā; pāda 3 vikṛtavṛtta; pāda 4 adhikākṣarā)',
       'ajñātasamavṛtta [5: Blg] (pāda 1 vikṛtavṛtta; pāda 4 adhikākṣarā)',
       'anuṣṭubh (ardham eva: asamīcīnā, [caturthāt ...] yujo j) atha vā ajñātasamavṛtta [4: yl] (pāda 1 vikṛtavṛtta)'],
      shape=(3676,), dtype=object)

In [30]:
f = open('unique_skr_out.txt', 'a')

for skr_out in df['skr_out'].unique():
    f.write(skr_out+"\n")

In [26]:
df['syllable_count'] = ""

for i, r in tqdm(df.iterrows(), total=df.shape[0]):
    verse = df.loc[i, 'sa']
    meter_info = MI.identify_meter(verse, resplit_option="resplit_lite", resplit_keep_midpoint=True, from_scheme="DEV")

    syllables = [x for x in meter_info.text_syllabified.split() if x.strip()]
    df.at[i, 'syllable_count'] = len(syllables)

100%|██████████| 74941/74941 [21:23<00:00, 58.39it/s]

In [28]:
df.head()

,sa,hi,skr_out,syllable_count
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56
1,ताभ्यः पुरुषमानयत्ता अब्रुवन् सुकृतं वतेति पुर...,वह उनके लिये पुरुष ले आया वे बोले'यह सुन्दर बन...,"upagīti (ardha 2: adhikamātrā, 27→28)",38
2,इति श्रीमहाभारते शान्तिपर्वणि आपद्धर्मपर्वणि ल...,इस प्रकार श्रीमहाभारत शान्तिपर्वके अन्तर्गत आप...,"āryā (ardha 1: ūnamātrā, 30→28; ardha 2: ūnamā...",37
3,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32
4,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32

In [ ]:
# 3 patterns 
# meter (
# meter [
# meter : 

# Lets search them and see if there are other pattern than these 
import re
pattern = r'^.+?[\(\[:]'


f = open('skr_out_without_bracket.txt', 'a')

for skr_out in df['skr_out'].unique():
    if bool(re.match(pattern, skr_out)):
        continue
    f.write(skr_out+"\n")
    
# Empty file result that means skrutable result only in these 3 formats

In [39]:
# Extracting meter name from these patterns 

# Two more patterns found; meter = and meter +

pattern = re.compile(r'^(.*?)\s*[\(\[:=+]')

def extract_meter(text):
    if not isinstance(text, str):
        return None

    m = pattern.match(text)
    if m:
        return m.group(1).strip()
    return None

In [40]:
df["skr_meter"] = df["skr_out"].apply(extract_meter)

In [41]:
df.head()

,sa,hi,skr_out,syllable_count,skr_meter
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56,vasantatilakā
1,ताभ्यः पुरुषमानयत्ता अब्रुवन् सुकृतं वतेति पुर...,वह उनके लिये पुरुष ले आया वे बोले'यह सुन्दर बन...,"upagīti (ardha 2: adhikamātrā, 27→28)",38,upagīti
2,इति श्रीमहाभारते शान्तिपर्वणि आपद्धर्मपर्वणि ल...,इस प्रकार श्रीमहाभारत शान्तिपर्वके अन्तर्गत आप...,"āryā (ardha 1: ūnamātrā, 30→28; ardha 2: ūnamā...",37,āryā
3,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh
4,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh

In [45]:
df['skr_meter'].unique()

array(['vasantatilakā', 'upagīti', 'āryā', 'anuṣṭubh', 'upajāti triṣṭubh',
       None, 'indravajrā', 'puṣpitāgrā', 'āryāgīti', 'śārdūlavikrīḍita',
       'ajñātasamavṛtta', 'mālinī', 'drutavilambita', 'upajāti jagatī',
       'mandākrāntā', 'pramāṇikā', 'udgīti', 'gīti', 'śālinī',
       'mattamayūra', 'vaṃśastha', 'bhujaṅgaprayāta', 'kanyā',
       'śikhariṇī', 'vidyumālā', 'pṛthvī', 'svāgatā', 'sragdharā',
       'rathoddhatā', 'upendravajrā', 'viyoginī', 'vaiśvadevī',
       'praharṣiṇī', 'toṭaka', 'somarājī', 'śaśivadanā', 'dodhaka',
       'rucirā', 'madhumatī', 'narkuṭaka', 'vidyullekhā', 'indravaṃśā',
       'vātormī', 'aparavaktra', 'aupacchandasika', 'mallikāmālā',
       'pañcacāmara', 'hariṇī', 'śravaṇābharaṇam', 'praharaṇakalikā',
       'tanumadhyamā', 'sragviṇī', 'madalekhā', 'cārucāmara', 'gajagati',
       'mālatī', 'tāmarasa', 'pañcakāvalī', 'kumāralalitā',
       'mañjubhāṣiṇī', 'śaśikalā', 'tvaritagati'], dtype=object)

In [46]:
df[df['skr_meter'].isna()].shape

(11669, 5)

In [48]:
df.isna().sum()

sa                    0
hi                    0
skr_out               0
syllable_count        0
skr_meter         11669
dtype: int64

# Chanda Detector

In [51]:
import sys
from pathlib import Path

sys.path.append(str(Path("chandas-detector").resolve()))

import chandas_detector

In [52]:
from chandas_detector import detect_meter, format_result

verse = """
काष्ठं जनः कुलधनैरनुरञ्जनीयस्
तन्नो यदुक्तमशिवं न हि तत्क्षमं ते।
नैसर्गिकी सुरभिणः कुसुमस्य सिद्धा
मूर्ध्नि स्थितिर्न चरणैरवताडनानि
"""

result = detect_meter(verse)

if result.confidence == "exact":
    print(f"Detected: {result.meter}")
else:
    print("Could not verify meter.")

# Print the formatted text diagnostic representation
print(format_result(result))

Detected: Vasantatilakā
============================================================
  Chandas Detector — Analysis Result
============================================================
  Pāda 1: GGLGLLLGLLGLGG  (14 syllables)
          [GGL | GLL | LGL | LGL | GG]
  Pāda 2: GGLGLLLGLLGLGG  (14 syllables)
          [GGL | GLL | LGL | LGL | GG]
  Pāda 3: GGLGLLLGLLGLGG  (14 syllables)
          [GGL | GLL | LGL | LGL | GG]
  Pāda 4: GGLGLLLGLLGLGL  (14 syllables)
          [GGL | GLL | LGL | LGL | GL]
------------------------------------------------------------
  ✓ Detected Meter : Vasantatilakā
    Gaṇa Structure : त भ ज ज ग ग
    Yati (Caesura)  : 8 + 6
    Confidence     : exact
============================================================

In [54]:
result.meter

'Vasantatilakā'

In [65]:
meter_codes = []

for r in tqdm(df.itertuples(index=False), total=len(df)):
    verse = r.sa.strip()
    result = detect_meter(verse)

    meter_codes.append(result.meter if result.confidence == "exact" else None)

df["meter_cd"] = meter_codes

  0%|          | 0/74941 [00:00<?, ?it/s]

100%|██████████| 74941/74941 [00:23<00:00, 3172.53it/s]
/tmp/ipykernel_474807/2030493013.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["meter_cd"] = meter_codes

In [66]:
df.head()

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56,vasantatilakā,Vasantatilakā
1,ताभ्यः पुरुषमानयत्ता अब्रुवन् सुकृतं वतेति पुर...,वह उनके लिये पुरुष ले आया वे बोले'यह सुन्दर बन...,"upagīti (ardha 2: adhikamātrā, 27→28)",38,upagīti,None
2,इति श्रीमहाभारते शान्तिपर्वणि आपद्धर्मपर्वणि ल...,इस प्रकार श्रीमहाभारत शान्तिपर्वके अन्तर्गत आप...,"āryā (ardha 1: ūnamātrā, 30→28; ardha 2: ūnamā...",37,āryā,None
3,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh,Anuṣṭubh
4,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh,Anuṣṭubh

In [67]:
df['meter_cd'].unique()

array(['Vasantatilakā', None, 'Anuṣṭubh', 'Śārdūlavikrīḍita', 'Mālinī',
       'Indravajrā', 'Śālinī', 'Vaṃśastha', 'Śikhariṇī', 'Upendravajrā',
       'Sragdharā'], dtype=object)

In [69]:
valid_syllable_count = {
    'Vasantatilakā':56,
    'Anuṣṭubh':32,
    'Śārdūlavikrīḍita':76,
    'Mālinī':60,
    'Indravajrā':44,
    'Śālinī':44,
    'Vaṃśastha':48,
    'Śikhariṇī':68,
    'Upendravajrā':44,
    'Sragdharā':84
}

In [70]:
df.isnull().sum()

sa                    0
hi                    0
skr_out               0
syllable_count        0
skr_meter         11669
meter_cd          45731
dtype: int64

In [72]:
df["comments"] = None

for row in tqdm(df.itertuples(index=True), total=len(df)):
    comments = []

    if row.meter_cd is not None:
        if (
            row.skr_meter is None
            or row.meter_cd.strip().lower() != row.skr_meter.strip().lower()
        ):
            comments.append("Skrutable Mismatch")

        if row.syllable_count != valid_syllable_count[row.meter_cd]:
            comments.append("Syllable Count Error")

    if comments:
        df.at[row.Index, "comments"] = " + ".join(comments)

/tmp/ipykernel_474807/139302383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["comments"] = None
100%|██████████| 74941/74941 [00:00<00:00, 618226.14it/s]

In [73]:
df.head()

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56,vasantatilakā,Vasantatilakā,None
1,ताभ्यः पुरुषमानयत्ता अब्रुवन् सुकृतं वतेति पुर...,वह उनके लिये पुरुष ले आया वे बोले'यह सुन्दर बन...,"upagīti (ardha 2: adhikamātrā, 27→28)",38,upagīti,None,None
2,इति श्रीमहाभारते शान्तिपर्वणि आपद्धर्मपर्वणि ल...,इस प्रकार श्रीमहाभारत शान्तिपर्वके अन्तर्गत आप...,"āryā (ardha 1: ūnamātrā, 30→28; ardha 2: ūnamā...",37,āryā,None,None
3,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh,Anuṣṭubh,None
4,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh,Anuṣṭubh,None

In [74]:
df['comments'].unique()

array([None, 'Skrutable Mismatch'], dtype=object)

In [76]:
df[df['comments'] == 'Skrutable Mismatch'].shape

(27, 7)

In [77]:
df[df['comments'] == 'Skrutable Mismatch']

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments
5140,चापपाणि: सुतीक्ष्येषु; कवची हेममालिक: सितप्राव...,उसके हाथमें धनुष और तीखे बाण शोभा पाते थे वह क...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
5917,नारदे तु गते स्वर्गे सर्वे ते पृथिवीभुजः विस्म...,नारदजीके स्वर्गलोकको चले जानेपर वे समस्त भूपाल...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
9491,"एष धारयिता सम्यक् चातुर्वर्ण्य, महाबलः शुभाशुभ...",यह महावली राजकुमार चारों वर्णोंको भलीभाँति धार...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
13891,तसात्‌ सङ्गो न कर्तव्य; ख्रीष ख्रेणेषु चेन्द्र...,अतः वाणी) कान और मन आदि इन्द्रियोसि क्षो और खी...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
22105,यावद्‌ देदेन्द्रियप्राणैरात्मन; सन्निकर्षणस्‌ ...,भगवान्‌ श्रीकृष्णने कहावस्तुतः प्रिय उद्धव ! स...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
23127,नीपार्जुनकदम्बानां पृथिव्यां चातिवृष्टिभि: गन्...,"पृथ्वीपर अत्यन्त वर्षा होनेके कारण नीप, अर्जुन...",na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
24690,"ताराचित्रपिनद्धाड़ं, स्वर्णकूबरभूषितम्‌ सुपताक...",उसके सारे अक्ग तारिकाओंके चित्रसे व्याप्त थे स...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
25464,एतस्मिन्नन्तरे क्रुद्ध/ कालनेमिर्महासुरः व्यवर...,इसी बीच कुपित हुआ महान्‌ असुर कालनेमि समुद्रकी...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
25996,"त्र्यक्षरं परमं ब्रह्म गोविन्द, त्र्यक्षरं परम...",गोविन्द' नाम के तीनों अक्षर परम ब्रह्म स्वरूप ...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
27493,परिरम्भो हि मे लोके दुर्लभः परमात्मनः अतस्त्वं...,संसारमें मुझ परमात्माका आलिङ्गन मिलना अत्यन्त ...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
27596,अहमास्माऽऽन्तरो बाह्योच्नाइत; सर्वदेहिनाम्‌ यथ...,"जैसे स्थूळ पञ्चयूर्तोमे बाहर, भीतरसर्त्र सूक्ष...",na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
32186,इत्युक्तो लोकनाथेन स्वयम्भू; प्रणिपत्य तम्‌ सह...,श्रीशुकदेवजी कहते हैँ परीक्षित्‌ ! जब अखिळलोका...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
33399,शुचिः सम्मुखमासीन; प्राणसंयमनादिभिः पिण्डं विश...,पहले स्नानादिसे शरीर और संतोष आदिसे अन्त: करणक...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
35020,विष्णु: श्रृड़समुद्धूतं प्रगृह्य विपुलं धनुः प...,उधर महाबाहु भगवान्‌ विष्णु श्रुड़से निर्मित हु...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
36426,वामनो हासुरेन्द्रस्य चिकीर्षु; कदनं महत्‌ क्षि...,भगवान्‌ वामन असुरराज बलिकी बड़ी भारी हानि करना...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
43053,यं न योगेन सांख्येन दानव्रततपोऽभ्वरेः व्याख्या...,"उद्धव बड़ेबड़े प्रयत्नशील साधक योग, सांख्य, द...",na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
45813,वत्सावते त्वपुत्राय वसुदेव:ः प्रतापवान्‌ अद्/ि...,शूरनन्दन प्रतापी वसुदेवजीने पुत्रहीन वत्सावानक...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
49420,प्रकृति; पुरुपश्चेति विकल्पः पुरुपर्षम एष वैका...,भगवान्‌ श्रीक्ष्णने कहाउद्भवजी ! प्रकृति और पु...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
52947,कपोती प्रथमं गर्भ गृह्ृती काल आगते अण्डानि सुष...,समय आनेपर कबूतरीको पहला गर्भ रहा उसने षँ 'पतिक...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
55421,तयोरेकतरो ह्यर्थः प्रकृति; सोभयात्मिका ज्ञानं ...,उनमेंसे एक वस्तुको प्रकृति कहते हैं उसीने जगत ...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
55854,तपस्येवाभवन् सर्वे सर्वे धर्ममनुव्रताः पृथिव्य...,धर्मात्मा राजा रामके राज्यमै पृथ्वीपर सच लोग त...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
57247,किं दानं किं तपः शौर्य किं सत्यसृतमुच्यते कस्त...,"आप मुझे दान, तपस्या, शूरता, सत्य ओर ऋका भी सहा...",na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
64169,"यदुनेवं महाभागो ब्रह्मण्येन सुमेधसा पृष्ट, सभा...",भगवान श्रीकृष्णने कहाउद्धव ! हमारे पूर्वज महार...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
67089,यथाग्निः सुसमृद्धाचि; करोत्येधांसि भस्मसात्‌ त...,उद्धव जैसे धधकती हुई आग लकड़ियोंके बड़े ढेरको...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
72681,"एवं, वर्णस्य वर्णस्य समुष्चीय सहस्रशः यथा समुद...",इसी प्रकार प्रत्येक वर्णके हजारों चुने हुए योद...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
72845,तत्तत्‌ सास्विकमेवेषां यद्‌ यद्‌ वृद्धा; प्रचक...,इनमेंसे शाब्नज्ञ महात्मा जिनकी प्रशंसा करते है...,na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch
73079,घान्यदावेखितन्तूनां रसतैजसचर्मणाम्‌ कालवाय्वम्...,"अनाज, लकडी, _हाथीदाँत आदि हड्डी, सूत, मधु, नमक...",na kiṃcid adhyavasitam,32,None,Anuṣṭubh,Skrutable Mismatch

In [78]:
df.to_csv("v3_gitapress_meter_analysed.csv", index=False)

In [79]:
df.isnull().sum()

sa                    0
hi                    0
skr_out               0
syllable_count        0
skr_meter         11669
meter_cd          45731
comments          74914
dtype: int64

In [80]:
df['skr_meter'].unique()

array(['vasantatilakā', 'upagīti', 'āryā', 'anuṣṭubh', 'upajāti triṣṭubh',
       None, 'indravajrā', 'puṣpitāgrā', 'āryāgīti', 'śārdūlavikrīḍita',
       'ajñātasamavṛtta', 'mālinī', 'drutavilambita', 'upajāti jagatī',
       'mandākrāntā', 'pramāṇikā', 'udgīti', 'gīti', 'śālinī',
       'mattamayūra', 'vaṃśastha', 'bhujaṅgaprayāta', 'kanyā',
       'śikhariṇī', 'vidyumālā', 'pṛthvī', 'svāgatā', 'sragdharā',
       'rathoddhatā', 'upendravajrā', 'viyoginī', 'vaiśvadevī',
       'praharṣiṇī', 'toṭaka', 'somarājī', 'śaśivadanā', 'dodhaka',
       'rucirā', 'madhumatī', 'narkuṭaka', 'vidyullekhā', 'indravaṃśā',
       'vātormī', 'aparavaktra', 'aupacchandasika', 'mallikāmālā',
       'pañcacāmara', 'hariṇī', 'śravaṇābharaṇam', 'praharaṇakalikā',
       'tanumadhyamā', 'sragviṇī', 'madalekhā', 'cārucāmara', 'gajagati',
       'mālatī', 'tāmarasa', 'pañcakāvalī', 'kumāralalitā',
       'mañjubhāṣiṇī', 'śaśikalā', 'tvaritagati'], dtype=object)

In [82]:
df['meter_cd'].unique()

array(['Vasantatilakā', None, 'Anuṣṭubh', 'Śārdūlavikrīḍita', 'Mālinī',
       'Indravajrā', 'Śālinī', 'Vaṃśastha', 'Śikhariṇī', 'Upendravajrā',
       'Sragdharā'], dtype=object)

# FInal analysis and split

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/home/shivraj-pg/v3_poetrygen_new/v3_gitapress_meter_analysed.csv")

df.head()

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56,vasantatilakā,Vasantatilakā,NaN
1,ताभ्यः पुरुषमानयत्ता अब्रुवन् सुकृतं वतेति पुर...,वह उनके लिये पुरुष ले आया वे बोले'यह सुन्दर बन...,"upagīti (ardha 2: adhikamātrā, 27→28)",38,upagīti,NaN,NaN
2,इति श्रीमहाभारते शान्तिपर्वणि आपद्धर्मपर्वणि ल...,इस प्रकार श्रीमहाभारत शान्तिपर्वके अन्तर्गत आप...,"āryā (ardha 1: ūnamātrā, 30→28; ardha 2: ūnamā...",37,āryā,NaN,NaN
3,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh,Anuṣṭubh,NaN
4,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,anuṣṭubh,Anuṣṭubh,NaN

In [4]:
df.isnull().sum()

sa                    0
hi                    0
skr_out               0
syllable_count        0
skr_meter         11669
meter_cd          45731
comments          74914
dtype: int64

In [6]:
df['skr_meter'].unique()

array(['vasantatilakā', 'upagīti', 'āryā', 'anuṣṭubh', 'upajāti triṣṭubh',
       nan, 'indravajrā', 'puṣpitāgrā', 'āryāgīti', 'śārdūlavikrīḍita',
       'ajñātasamavṛtta', 'mālinī', 'drutavilambita', 'upajāti jagatī',
       'mandākrāntā', 'pramāṇikā', 'udgīti', 'gīti', 'śālinī',
       'mattamayūra', 'vaṃśastha', 'bhujaṅgaprayāta', 'kanyā',
       'śikhariṇī', 'vidyumālā', 'pṛthvī', 'svāgatā', 'sragdharā',
       'rathoddhatā', 'upendravajrā', 'viyoginī', 'vaiśvadevī',
       'praharṣiṇī', 'toṭaka', 'somarājī', 'śaśivadanā', 'dodhaka',
       'rucirā', 'madhumatī', 'narkuṭaka', 'vidyullekhā', 'indravaṃśā',
       'vātormī', 'aparavaktra', 'aupacchandasika', 'mallikāmālā',
       'pañcacāmara', 'hariṇī', 'śravaṇābharaṇam', 'praharaṇakalikā',
       'tanumadhyamā', 'sragviṇī', 'madalekhā', 'cārucāmara', 'gajagati',
       'mālatī', 'tāmarasa', 'pañcakāvalī', 'kumāralalitā',
       'mañjubhāṣiṇī', 'śaśikalā', 'tvaritagati'], dtype=object)

In [7]:
df['meter_cd'].unique()

array(['Vasantatilakā', nan, 'Anuṣṭubh', 'Śārdūlavikrīḍita', 'Mālinī',
       'Indravajrā', 'Śālinī', 'Vaṃśastha', 'Śikhariṇī', 'Upendravajrā',
       'Sragdharā'], dtype=object)

In [9]:
skr_cd_meter_dict = {
    'vasantatilakā': 'Vasantatilakā',
    'anuṣṭubh': 'Anuṣṭubh',
    'śārdūlavikrīḍita': 'Śārdūlavikrīḍita',
    'mālinī': 'Mālinī',
    'indravajrā': 'Indravajrā',
    'śālinī': 'Śālinī',
    'vaṃśastha': 'Vaṃśastha',
    'śikhariṇī': 'Śikhariṇī',
    'upendravajrā': 'Upendravajrā',
    'sragdharā':'Sragdharā'
}

In [10]:
df['skr_meter'] = df['skr_meter'].replace(skr_cd_meter_dict)

In [12]:
final_df = df[df['skr_meter'] == df['meter_cd']]
final_df.shape

(29183, 7)

In [13]:
final_df['skr_meter'].unique()

array(['Vasantatilakā', 'Anuṣṭubh', 'Śārdūlavikrīḍita', 'Mālinī',
       'Indravajrā', 'Śālinī', 'Vaṃśastha', 'Śikhariṇī', 'Upendravajrā',
       'Sragdharā'], dtype=object)

In [14]:
final_df['meter_cd'].unique()

array(['Vasantatilakā', 'Anuṣṭubh', 'Śārdūlavikrīḍita', 'Mālinī',
       'Indravajrā', 'Śālinī', 'Vaṃśastha', 'Śikhariṇī', 'Upendravajrā',
       'Sragdharā'], dtype=object)

In [15]:
final_df.head()

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56,Vasantatilakā,Vasantatilakā,NaN
3,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN
4,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN
5,स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन...,वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर च...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN
7,अहोरात्रेक्षणो दिव्यो वेदाड़ः श्रुतिभूषण: आज्य...,"दिन और रात्रि उनके नेत्र हैं, वे दिव्यस्वरूप ह...","anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN

In [16]:
final_df.to_csv("v3_gitapress_skr_equal_verifier.csv", index=False)

# n shot data prep

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Files/v3_gitapress_final.csv")
df.shape

(29183, 9)

In [3]:
df['split'].unique()

<ArrowStringArray>
['train', 'test', 'val']
Length: 3, dtype: str

In [4]:
df['meter_cd'].unique()

<ArrowStringArray>
[   'Vasantatilakā',         'Anuṣṭubh', 'Śārdūlavikrīḍita',
           'Mālinī',       'Indravajrā',           'Śālinī',
        'Vaṃśastha',        'Śikhariṇī',     'Upendravajrā',
        'Sragdharā']
Length: 10, dtype: str

In [5]:
examples = (
    df[df["split"] == "train"]
    .groupby("meter_cd", group_keys=False)
    .head(3)
)

examples

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments,prompt,split
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56,Vasantatilakā,Vasantatilakā,NaN,Objective:\n\nGenerate a sanskrit verse in Vas...,train
1,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
2,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
3,स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन...,वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर च...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
18,रत्नैः कल्पितमासनं हिमजलैः स्नानं च दिव्याम्बर...,हे दयानिधे ! हे पशुपते ! हे देव ! यह रत्ननिर्म...,śārdūlavikrīḍita [19: msjsttg],76,Śārdūlavikrīḍita,Śārdūlavikrīḍita,NaN,Objective:\n\nGenerate a sanskrit verse in Śār...,train
22,त्वयि विमुखमिवोच्चैस्तापभारं वहन्तं तव भजनवदन्...,आपसे विमुख पुरुष की भाँति जो भारी ताप का भार व...,mālinī [15: nnmyy],60,Mālinī,Mālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Māl...,train
27,श्रीनाथ विश्वेश्वर विश्वमूर्ते श्रीदेवकीनन्दन ...,हे जिह्वे ! तू 'श्रीनाथ ! सर्वेश्वर ! श्रीविष्...,indravajrā [11: ttjgg],44,Indravajrā,Indravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Ind...,train
94,हे दुःखभञ्जक विभो गिरिजेश शूलिन्‌ हे वेदशास्त्...,"हे समस्त दुःखोंके विध्वंसक, विभु, हे गिरिजेश!,...",vasantatilakā [14: tBjjgg],56,Vasantatilakā,Vasantatilakā,NaN,Objective:\n\nGenerate a sanskrit verse in Vas...,train
113,अयि सबल मुरारे पाणिजानुप्रचारैः किमपि भवनभागान...,हे बलरामसहित मुरारि श्रीकृष्ण ! अब आप दोनों घु...,mālinī [15: nnmyy],60,Mālinī,Mālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Māl...,train
129,योगीशमिश्रमुखपङ्कजनिर्गतं यो विश्चेश्वराष्टकमि...,जो व्यक्ति योगीशमिश्रके मुखकमलसे निर्गत इस विश...,vasantatilakā [14: tBjjgg],56,Vasantatilakā,Vasantatilakā,NaN,Objective:\n\nGenerate a sanskrit verse in Vas...,train
138,मातर्जाह्नवि शम्भुसङ्गवलिते मौलौ निधायाञ्जलिं ...,हे शिवकी संगिनी मातः गङ्गे ! शरीर शान्त होनेके...,śārdūlavikrīḍita [19: msjsttg],76,Śārdūlavikrīḍita,Śārdūlavikrīḍita,NaN,Objective:\n\nGenerate a sanskrit verse in Śār...,train
172,स्तम्भे घट्टयतो हिरण्यकशिपोः कर्णौ समाचूर्णय न...,हिरण्यकशिपु के खंभे पर प्रहार करते ही आपका ऐसा...,śārdūlavikrīḍita [19: msjsttg],76,Śārdūlavikrīḍita,Śārdūlavikrīḍita,NaN,Objective:\n\nGenerate a sanskrit verse in Śār...,train
176,स तद्वचः शत्रुनिबर्हणे रत स्तथा चकारावितथं बृह...,भीष्मजी कहते हैं युधिष्ठिर ! शत्रुओंके संहारमे...,vaṃśastha [12: jtjr],48,Vaṃśastha,Vaṃśastha,NaN,Objective:\n\nGenerate a sanskrit verse in Vaṃ...,train
217,विशालश्रीखण्डद्रवमृगमदाकीर्णघुसृण प्रसूनव्यामि...,"हे भगवति ! जिसमें विशाल चन्दनके रस, कस्तूरी और...",śikhariṇī [17: ymnsBlg],68,Śikhariṇī,Śikhariṇī,NaN,Objective:\n\nGenerate a sanskrit verse in Śik...,train
235,स्वर्गाङ्गणे वेणुमृदङ्गशङ्खभेरीनिनादैरुपगीयमान...,"स्वर्ग आँगनमें वेणु, मृदङ्ग, शङ्ख तथा भेरीकी म...",indravajrā [11: ttjgg],44,Indravajrā,Indravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Ind...,train
265,पवनतनयहस्तन्यस्तपादाम्बुजात्मा कलशभववचोभिः प्र...,जो हनुमान्जीके हाथोंपर अपने चरणकमलोंको रखे हुए...,mālinī [15: nnmyy],60,Mālinī,Mālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Māl...,train
335,प्रदीप्तरत्नोज्ज्चलकुण्डलायै स्फुरन्महापन्नगभू...,भगवती पार्वती प्रदीप्त रत्नोंके उज्ज्वल कुण्डल...,upendravajrā [11: jtjgg],44,Upendravajrā,Upendravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Upe...,train
357,गतोऽयमाश्चर्यमयीं भवत्पुरीं गृहेषु शैब्याभवनं ...,तदनन्तर आश्चर्यमयी कारीगरी से सुशोभित आपकी पुर...,vaṃśastha [12: jtjr],48,Vaṃśastha,Vaṃśastha,NaN,Objective:\n\nGenerate a sanskrit verse in Vaṃ...,train
446,अङ्गुष्ठमात्रो रवितुल्यरूपः सङ्कल्पहङ्कारसमन्व...,"जो अँगूठेके बराबर परिमाणवाला, सूर्यके समान ज्य...",indravajrā [11: ttjgg],44,Indravajrā,Indravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Ind...,train
527,प्रजानाथं नाथ प्रसभमभिकं स्वां दुहितरं गतं रोह...,हे स्वामिन्‌! कामुक ब्रह्माने अपनी दुहितासे हठ...,śikhariṇī [17: ymnsBlg],68,Śikhariṇī,Śikhariṇī,NaN,Objective:\n\nGenerate a sanskrit verse in Śik...,train
549,सत्त्वेनासत्तया वा न च खलु सदसत्त्वेन निर्वाच्...,"जो अविद्या न सती, न असती है और न सदसती ही है, ...",sragdharā [21: mrBnyyy],84,Sragdharā,Sragdharā,NaN,Objective:\n\nGenerate a sanskrit verse in Sra...,train
639,सत्त्वोन्मेषात् कदाचित् खलु विषयरसे दोषबोधेऽपि...,भूमन् ! 'सत्त्वगुण के उद्रेक से कभीकभी विषयरस ...,sragdharā [21: mrBnyyy],84,Sragdharā,Sragdharā,NaN,Objective:\n\nGenerate a sanskrit verse in Sra...,train
643,भूमिर्भारेण भग्ना दशवदनमुखाशेषरक्षोगणानां धृत्...,एक बार रावण आदि राक्षसोंके भारसे व्यथित हो पृथ...,sragdharā [21: mrBnyyy],84,Sragdharā,Sragdharā,NaN,Objective:\n\nGenerate a sanskrit verse in Sra...,train
688,नमामि कल्याणमचिन्त्यरूपं नमामि विश्वोद्भवबीजरू...,"जिनका रूप चित्तनका विषय नहीं है, उन कल्याणमय श...",upendravajrā [11: jtjgg],44,Upendravajrā,Upendravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Upe...,train
694,एको देवः सर्वभूतेषु गूढः सर्वव्यापी सर्वभूतान्...,समस्त प्राणियोंमें स्थित एक देव है; वह सर्वव्य...,śālinī [11: mttgg],44,Śālinī,Śālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Śāl...,train
827,अहो आरण्योऽयं मृग इति हसन्तं बहुतरै र्दुरुक्तै...,भगवन् ! आपको देखते ही जब वह 'अहो ! यह तो एक जं...,śikhariṇī [17: ymnsBlg],68,Śikhariṇī,Śikhariṇī,NaN,Objective:\n\nGenerate a sanskrit verse in Śik...,train
1008,कदा पुनः शङ्खरथाङ्गकल्पकध्व नारविन्दाङ्कुशवज्र...,"हे वामन ! शङ्ख, चक्र, कल्पवृक्ष, ध्वजा, कमल,अङ...",vaṃśastha [12: jtjr],48,Vaṃśastha,Vaṃśastha,NaN,Objective:\n\nGenerate a sanskrit verse in Vaṃ...,train
1298,†त्वमेव माता च पिता त्वमेव त्वमेव बन्धुश्च सखा...,"हे देवदेव ! तुम ही मेरी माता हो, तुम ही पिता ह...",upendravajrā [11: jtjgg],44,Upendravajrā,Upendravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Upe...,train
1420,त्वद्वाहं तं सक्षुधं तृक्षसूनुं मीनं कश्चिज्जक...,"आपके वाहनभूत गरुड़ भूख से व्याकुल थे, अतः वे क...",śālinī [11: mttgg],44,Śālinī,Śālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Śāl...,train
2304,तस्मिन् काले कालिय: क्ष्वेलदर्पात् सर्पारातेः ...,"उन्हीं दिनों की बात है, कालियनाग विषमद से उन्म...",śālinī [11: mttgg],44,Śālinī,Śālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Śāl...,train

In [6]:
df = df.drop(examples.index).reset_index(drop=True)

In [7]:
print(df.loc[0]['prompt'])

Objective:

Generate a sanskrit verse in Anuṣṭubh meter based on a given meaning or theme while strictly following the metrical (?and rhyme) rules.

Rules of Chandas:
Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

The goal is to generate Sanskrit verse that follows the anushtup meter rules for the given input translation.
RULES:
Verse Rules:
The verse contains 32 syllables/akshara and 4 padas in total.
The verse is divided in 2 lines, each containing 16 syllables.
Each line is divided into 2 padas (quartets),each containing exactly 8 syllables.
The fifth syllable of every pada must be LAGHU or short.
The sixth syllable of every pada must be GURU or long.
The seventh syllable of the second and the fourth pada must be HRASVA
The seventh syllable of the first and third paada must be DEERGHA

Language:
The generated verse must be in sanskrit in Devanagri script.
The Input given is in the hindi.
Do NOT include English words, transliteration, labels, or explanations.

Output Format:
(Output exactly 4 lines, one pada per line. Nothing else.)

In [8]:
example_map = {}

for meter, group in examples.groupby("meter_cd"):
    prompt_examples = ""

    for i, (_, row) in enumerate(group.iterrows(), start=1):
        prompt_examples += f"""
Example {i}:
Meaning:
{row['hi']}

Sanskrit Verse:
{row['sa']}

"""

    example_map[meter] = prompt_examples

In [9]:
print(example_map['Anuṣṭubh'])

Example 1:
Meaning:
इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह नहीं रखना चाहिये भोगों में जो आसक्ति होती है, वह दुःखरूप ही है धन पाकर भी उसे धर्ममें ही लगा देना चाहिये काम भोगोंको तो सर्वथा त्याग ही देना चाहिये

Sanskrit Verse:
न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्यार्थमुपयुञ्जीत धर्मं कामान् विसर्जयेत् ॥


Example 2:
Meaning:
कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्रेष्ठ पुरुष सब पापोंसे छूटते हैं और जो पापीलोग अपने शरीरपोषणके लिये ही पकाते हैं, वे तो पापको ही खाते हैं ॥

Sanskrit Verse:
यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भुञ्जते ते त्वयं पापा ये पचन्त्यात्मकारणात् ॥


Example 3:
Meaning:
वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर चतु रंगिणी सेनाके साथ शक्तिशाली अर्जुनने यहीं पड़ाव डाला ॥

Sanskrit Verse:
स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन चतुरङ्गेण निवेशमकरोत् प्रभुः ॥

In [10]:
def update_prompt(row):
    return row["prompt"] + example_map[row["meter_cd"]]

df["prompt"] = df.apply(update_prompt, axis=1)

In [11]:
print(df.loc[0]['prompt'])

Objective:

Generate a sanskrit verse in Anuṣṭubh meter based on a given meaning or theme while strictly following the metrical (?and rhyme) rules.

Rules of Chandas:
Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

The goal is to generate Sanskrit verse that follows the anushtup meter rules for the given input translation.
RULES:
Verse Rules:
The verse contains 32 syllables/akshara and 4 padas in total.
The verse is divided in 2 lines, each containing 16 syllables.
Each line is divided into 2 padas (quartets),each containing exactly 8 syllables.
The fifth syllable of every pada must be LAGHU or short.
The sixth syllable of every pada must be GURU or long.
The seventh syllable of the second and the fourth pada must be HRASVA
The seventh syllable of the first and third paada must be DEERGHA

Language:
The generated verse must be in sanskrit in Devanagri script.
The Input given is in the hindi.
Do NOT include English words, transliteration, labels, or explanations.

Output Format:
(Output exactly 4 lines, one pada per line. Nothing else.)

Example 1:
Meaning:
इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह नहीं रखना चाहिये भोगों में जो आसक्ति होती है, वह दुःखरूप ही है धन पाकर भी उसे धर्ममें ही लगा देना चाहिये काम भोगोंको तो सर्वथा त्याग ही देना चाहिये

Sanskrit Verse:
न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्यार्थमुपयुञ्जीत धर्मं कामान् विसर्जयेत् ॥


Example 2:
Meaning:
कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्रेष्ठ पुरुष सब पापोंसे छूटते हैं और जो पापीलोग अपने शरीरपोषणके लिये ही पकाते हैं, वे तो पापको ही खाते हैं ॥

Sanskrit Verse:
यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भुञ्जते ते त्वयं पापा ये पचन्त्यात्मकारणात् ॥


Example 3:
Meaning:
वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर चतु रंगिणी सेनाके साथ शक्तिशाली अर्जुनने यहीं पड़ाव डाला ॥

Sanskrit Verse:
स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन चतुरङ्गेण निवेशमकरोत् प्रभुः ॥

In [12]:
print(df.loc[28882]['prompt'])

Objective:

Generate a sanskrit verse in Śikhariṇī meter based on a given meaning or theme while strictly following the metrical (?and rhyme) rules.

Rules of Chandas:
Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 68 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 17 syllables.
The pattern of syllables in every pāda must be: यगण (LGG), मगण (GGG), नगण (LLL), सगण (LLG), भगण (GLL), followed by a Laghu (L) and a Guru (G). A caesura (yati) occurs after the 6th syllable.
The complete pattern for each pāda is: LGG GGG LLL LLG GLL LG.
L means Laghu, G means Guru.

Language:
The generated verse must be in sanskrit in Devanagri script.
The Input given is in the hindi.
Do NOT include English words, transliteration, labels, or explanations.

Output Format:
(Output exactly 4 lines, one pada per line. Nothing else.)

Example 1:
Meaning:
हे भगवति ! जिसमें विशाल चन्दनके रस, कस्तूरी और केसरके फूल मिले हुए हैं ऐसे तुम्हारे अनुलेपनके जलको और चलते हुए तुम्हारे चरणोंकी धूलिको ही लेकर ब्रह्माजी सुरपुरकी कमलनयनी वनिताओं की सृष्टि करते हैं ॥

Sanskrit Verse:
विशालश्रीखण्डद्रवमृगमदाकीर्णघुसृण प्रसूनव्यामिश्रं भगवति तवाभ्यङ्गसलिलम् समादाय स्रष्टा चलितपदपांसून्निजकरैः समाधत्ते सृष्टिं विबुधपुरपङ्केरुहदृशाम् ॥


Example 2:
Meaning:
हे स्वामिन्‌! कामुक ब्रह्माने अपनी दुहितासे हठपूर्वक रमण करनेकी इच्छा की वह लज्जासे मृगी बनकर भागी; तब ब्रह्मा भी मृग बनकर उसके पीछे दौड़े आपने भी उन्हें दण्ड देनेके लिये मृगके शिकारीके वेगके समान हाथमें धनुष लेकर बाण चला दिया स्वर्गमें जानेपर भी ब्रह्मा आपके बाणसे भयभीत हो रहे हैं उन्हें बाणने आज भी नहीं छोड़ा है; अर्थात्‌ ब्रह्मा 'मृगशिरा' नक्षत्र बनकर भागे तो बाण 'आर्द्रा' नक्षत्र बनकर आज भी पीछा करता है' ॥

Sanskrit Verse:
प्रजानाथं नाथ प्रसभमभिकं स्वां दुहितरं गतं रोहिद्भूतां रिरमयिषुमृष्यस्य वपुषा धनुष्पाणेर्यातं दिवमपि सपत्राकृतममुं त्रसन्तं तेऽद्यापि त्यजति न मृगव्याधरभसः॥


Example 3:
Meaning:
भगवन् ! आपको देखते ही जब वह 'अहो ! यह तो एक जंगली सूकर हैं' यों हँसता हुआ बहुतसी कटूक्तियोंद्वारा आपको कष्ट पहुँचाने लगा तब आपने भी उस दितिपुत्र की अवज्ञा करके अपने दंष्ट्राग्रभागपर स्थित भूमि को भयचकित देखकर उसे अपनी अप्रमेय महिमा से प्रलयपयोधि के जलपर स्थापित कर दिया और स्वयं बलपूर्वक युद्ध करने के लिये उद्यत हो गये ॥

Sanskrit Verse:
अहो आरण्योऽयं मृग इति हसन्तं बहुतरै र्दुरुक्तैर्विध्यन्तं दितिसुतमवज्ञाय भगवन् महीं दृष्ट्वा दंष्ट्रा शिरसि चकितां स्वेन महसा पयोधावाधाय प्रसभमुदयुङ्क्था मृधविधौ ॥

In [13]:
df.shape

(29153, 9)

In [14]:
df.to_csv("Files/v3_gitapress_final_3shot_prompts.csv", index=False)

In [15]:
for i, row in df.iterrows():
    prompt = row["prompt"]

    missing = [j for j in range(1, 4) if f"Example {j}" not in prompt]

    if missing:
        print(f"Prompt error at index {i}: Missing Example(s) {missing}")