# LG PATTERN EXTRACTOR

In [12]:
import pandas as pd
from skrutable.meter_identification import MeterIdentifier
import re
from tqdm import tqdm

MI = MeterIdentifier()

In [13]:
df = pd.read_csv("/home/shivraj-pg/poetrygen_new/Files/v3_gitapress_final.csv")

df.head()

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments,prompt,split
0,ब्रह्मादयः सुरगणा मुनयोऽथ सिद्धाः सत्त्वैकतानम...,प्रह्लादजी बोले जिनकी बुद्धि एकमात्र सत्त्वगुण...,vasantatilakā [14: tBjjgg],56,Vasantatilakā,Vasantatilakā,NaN,Objective:\n\nGenerate a sanskrit verse in Vas...,train
1,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
2,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
3,स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन...,वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर च...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
4,अहोरात्रेक्षणो दिव्यो वेदाड़ः श्रुतिभूषण: आज्य...,"दिन और रात्रि उनके नेत्र हैं, वे दिव्यस्वरूप ह...","anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train

In [14]:
df_one_per_meter = df.groupby("meter_cd", group_keys=False).sample(n=1)

df_one_per_meter

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments,prompt,split
5931,गीतं नृत्यं विचित्रं च वादित्रं विविधं तथा शिक...,राजन् ! मैं विराटनगरकी स्त्रियोंको गीत गाने वि...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
27114,श्रीकृष्ण गोविन्द हरे मुरारे हे नाथ नारायण वास...,हे जिले ! तू 'श्रीकृष्ण ! गोविन्द ! हरे ! मुरा...,indravajrā [11: ttjgg],44,Indravajrā,Indravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Ind...,train
27399,शिशिर किरणधारी शैलबालाविहारी भव जलनिधितारी योग...,"जो चन्द्रकलाको धारण किये हैं, पार्वती रमण हैं,...",mālinī [15: nnmyy],60,Mālinī,Mālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Māl...,train
639,सत्त्वोन्मेषात् कदाचित् खलु विषयरसे दोषबोधेऽपि...,भूमन् ! 'सत्त्वगुण के उद्रेक से कभीकभी विषयरस ...,sragdharā [21: mrBnyyy],84,Sragdharā,Sragdharā,NaN,Objective:\n\nGenerate a sanskrit verse in Sra...,train
3127,षडङ्गयोगान्न तु नैव शुद्धं मनोविनाशान्न तु नैव...,"षडंगयोगसे भी आत्मा शुद्ध नहीं होता, मनका नाश ह...",upendravajrā [11: jtjgg],44,Upendravajrā,Upendravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Upe...,train
20554,त्वां शीलरूपचरितैः परमप्रकृष्टसत्वेन साच्चिकतय...,"आसुरीप्रकृतिवाले मनुष्य आपके लोकोत्तर शील, रूप...",vasantatilakā [14: tBjjgg],56,Vasantatilakā,Vasantatilakā,NaN,Objective:\n\nGenerate a sanskrit verse in Vas...,train
25073,तवामृतस्यन्दिनि पादपङ्कजे निवेशितात्मा कथमन्यद...,जो पुरुष आपके अमृतवर्षी चरणकमलों में दत्तचित्त...,vaṃśastha [12: jtjr],48,Vaṃśastha,Vaṃśastha,NaN,Objective:\n\nGenerate a sanskrit verse in Vaṃ...,train
7698,कृपापारावारां तपनतनयां तापशमनीं मुरारिप्रेयस्क...,"जो कृपाकी समुद्र, सूर्यकुमारी, तापको शान्त करन...",śikhariṇī [17: ymnsBlg],68,Śikhariṇī,Śikhariṇī,NaN,Objective:\n\nGenerate a sanskrit verse in Śik...,val
5002,यत् ते पृष्टं तन्मया चोपदिष्टं याथातथ्यं तद्वि...,राजन्! तुमने जो पूछा था उसके उत्तरमें मैंने तु...,śālinī [11: mttgg],44,Śālinī,Śālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Śāl...,val
13229,रे रे चातक सावधानमनसा मित्र क्षणं श्रूयतामम्मो...,अरे मित्र पपीहे ! सावधानमनसे जरा एक क्षण सुन त...,śārdūlavikrīḍita [19: msjsttg],76,Śārdūlavikrīḍita,Śārdūlavikrīḍita,NaN,Objective:\n\nGenerate a sanskrit verse in Śār...,train

In [20]:
import re

for i, r in df_one_per_meter.iterrows():

    input_string = r['sa']

    verse = MI.identify_meter(
        input_string,
        from_scheme='DEV',
        resplit_option='resplit_lite'
    )

    summary = verse.summarize()
    
    patterns = re.findall(
        r'^([lg]+)\s+\{m:',
        summary,
        re.MULTILINE
    )[:4]


    print(r['meter_cd'])
    print("-------------------------------------------------------------------------")
    print(summary)
    print("-------------------------------------------------------------------------")
    print(patterns)
    print("-------------------------------------------------------------------------")
    print("-------------------------------------------------------------------------")

Anuṣṭubh
-------------------------------------------------------------------------
gglglggg    {m: 14}    [8: trgg]
llgglgll    {m: 11}    [8: srll]
glgglggg    {m: 14}    [8: rrgg]
gglllglg    {m: 12}    [8: tslg]

   sau    hā   rda    cā    pi    me   tva   tto
     g     g     l     g     l     g     g     g
    na    ka    dā    ci  tpra    hā   sya    ti
     l     l     g     g     l     g     l     l
    pu   ṣka    ra  tvaṃ    hi    me  bhrā    tā
     g     l     g     g     l     g     g     g
   saṃ    jī    va    śa    ra   daḥ    śa   tam
     g     g     l     l     l     g     l     g

anuṣṭubh (1,2: pathyā; 3,4: pathyā)

-------------------------------------------------------------------------
['gglglggg', 'llgglgll', 'glgglggg', 'gglllglg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Indravajrā
-------------------------------------------------------------------------
gglggllglgg    {m: 18}    [11: ttjgg]
gglggllglgl    {m: 17}    [11: ttjgl]
gglggllglgl    {m: 17}    [11: ttjgl]
gglggllglgl    {m: 17}    [11: ttjgl]

    du   rvā    sa    so    vā   kya    mu    pe   tya    kṛ   ṣṇā
     g     g     l     g     g     l     l     g     l     g     g
    sā    cā   bra    vī   tkā    na    na    vā    si    nī    śa
     g     g     l     g     g     l     l     g     l     g     l
    ma  ntaḥ   pra    vi  ṣṭaṃ    ma    na    sā    ju    hā    va
     g     g     l     g     g     l     l     g     l     g     l
    go    vi   nda    dā    mo    da    ra    mā   dha    ve    ti
     g     g     l     g     g     l     l     g     l     g     l

indravajrā [11: ttjgg]

-------------------------------------------------------------------------
['gglggllglgg', 'gglggllglgl', 'gglggllglgl', 'gglggllglgl']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Mālinī
-------------------------------------------------------------------------
llllllggglgglgg    {m: 22}    [15: nnmyy]
llllllggglgglgg    {m: 22}    [15: nnmyy]
llllllggglgglgg    {m: 22}    [15: nnmyy]
llllllggglgglgg    {m: 22}    [15: nnmyy]

   bha    va    ti    vi   dhṛ    ta   śai    le    bā    li    kā   bhi   rva    ya  syai
     l     l     l     l     l     l     g     g     g     l     g     g     l     g     g
    ra    pi    vi    hi    ta    vi    lā   saṃ    ke    li    lā    pā    di    lo    le
     l     l     l     l     l     l     g     g     g     l     g     g     l     g     g
    sa    vi   dha    mi    li    ta   dhe    nū    re    ka    ha   ste    na    ka   ṇḍū
     l     l     l     l     l     l     g     g     g     l     g     g     l     g     g
    ya    ti    sa    ti    pa    śu    pā    lā   sto    ṣa   mai    ṣa   nta    sa   rve
     l     l     l     l     l     l     g     g     g     l     g     g     l     g     g

mālinī [15: nnmyy]

-------------------------------------------------------------------------
['llllllggglgglgg', 'llllllggglgglgg', 'llllllggglgglgg', 'llllllggglgglgg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Sragdharā
-------------------------------------------------------------------------
gggglggllllllgglgglgg    {m: 33}    [21: mrBnyyy]
gggglggllllllgglgglgg    {m: 33}    [21: mrBnyyy]
gggglggllllllgglgglgg    {m: 33}    [21: mrBnyyy]
gggglggllllllgglgglgg    {m: 33}    [21: mrBnyyy]

     ā   dau    ka   rma   pra    sa   ṅgā   tka    la    ya    ti    ka    lu   ṣaṃ    mā    tṛ    ku  kṣau  sthi   taṃ   māṃ
     g     g     g     g     l     g     g     l     l     l     l     l     l     g     g     l     g     g     l     g     g
    vi   ṇmū   trā    me  dhya    ma  dhye   kva   tha    ya    ti    ni    ta   rāṃ    jā   ṭha    ro    jā    ta    ve   dāḥ
     g     g     g     g     l     g     g     l     l     l     l     l     l     g     g     l     g     g     l     g     g
    ya   dya  dvai    ta   tra   duḥ  khaṃ   vya   tha    ya    ti    ni    ta   rāṃ    śa   kya    te    ke    na    va  ktuṃ
     g     g     g     g     l     g     g     l     l     l     l     l     l     g     g     l     g     g     l     g     g
   kṣa   nta   vyo    me   'pa    rā  dhaḥ    śi    va    śi    va    śi    va   bho   śrī    ma    hā    de    va    śa  mbho
     g     g     g     g     l     g     g     l     l     l     l     l     l     g     g     l     g     g     l     g     g

sragdharā [21: mrBnyyy]

-------------------------------------------------------------------------
['gggglggllllllgglgglgg', 'gggglggllllllgglgglgg', 'gggglggllllllgglgglgg', 'gggglggllllllgglgglgg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Upendravajrā
-------------------------------------------------------------------------
lglggllglgl    {m: 16}    [11: jtjgl]
lglggllglgl    {m: 16}    [11: jtjgl]
lglggllglgl    {m: 16}    [11: jtjgl]
lglggllglgg    {m: 17}    [11: jtjgg]

     a    kā    ra    ṇā    yā   khi    la    kā    ra    ṇā    ya
     l     g     l     g     g     l     l     g     l     g     l
    na    mo    ma    hā    kā    ra    ṇa    kā    ra    ṇā    ya
     l     g     l     g     g     l     l     g     l     g     l
    na    mo  'stu    kā    lā    na    la    lo    ca    nā    ya
     l     g     l     g     g     l     l     g     l     g     l
    kṛ    tā    ga   saṃ    mā    ma    va    vi   śca    mū    te
     l     g     l     g     g     l     l     g     l     g     g

upendravajrā [11: jtjgg]

-------------------------------------------------------------------------
['lglggllglgl', 'lglggllglgl', 'lglggllglgl', 'lglggllglgg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Vasantatilakā
-------------------------------------------------------------------------
gglglllgllglgl    {m: 20}    [14: tBjjgl]
gglglllgllglgg    {m: 21}    [14: tBjjgg]
gglglllgllglgg    {m: 21}    [14: tBjjgg]
gglglllgllglgg    {m: 21}    [14: tBjjgg]

   śau    ri   stu   dhī    ra    mu    ni    ma   ṇḍa    la    ce    ta    so   'pi
     g     g     l     g     l     l     l     g     l     l     g     l     g     l
    dū    ra  sthi   taṃ    va    pu    ru    dī  kṣya    ni    je   kṣa    ṇā  bhyā
     g     g     l     g     l     l     l     g     l     l     g     l     g     g
    mā    na   nda    vā   ṣpa    pu    la    ko   dga    ma    ga   dga    dā  dras
     g     g     l     g     l     l     l     g     l     l     g     l     g     g
    tu   ṣṭā    va    dṛ   ṣṭi    ma    ka    ra   nda    ra   saṃ   bha    va  ntam
     g     g     l     g     l     l     l     g     l     l     g     l     g     g

vasantatilakā [14: tBjjgg]

-------------------------------------------------------------------------
['gglglllgllglgl', 'gglglllgllglgg', 'gglglllgllglgg', 'gglglllgllglgg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Vaṃśastha
-------------------------------------------------------------------------
lglggllglglg    {m: 18}    [12: jtjr]
lglggllglglg    {m: 18}    [12: jtjr]
lglggllglglg    {m: 18}    [12: jtjr]
lglggllglglg    {m: 18}    [12: jtjr]

    tva     da  ṅghri     mu    ddi    śya     ka     dā     pi     ke     na    cid
      l      g      l      g      g      l      l      g      l      g      l      g
     ya    thā     ta    thā     vā     pi     sa     kṛ    tkṛ     to   'ñja    liḥ
      l      g      l      g      g      l      l      g      l      g      l      g
     ta    dai     va     mu    ṣṇā    tya     śu    bhā    nya     śe     ṣa    taḥ
      l      g      l      g      g      l      l      g      l      g      l      g
     śu    bhā     ni     pu    ṣṇā     ti     na     jā     tu     hī     ya     te
      l      g      l      g      g      l      l      g      l      g      l      g

vaṃśastha [12: jtjr]

-------------------------------------------------------------------------
['lglggllglglg', 'lglggllglglg', 'lglggllglglg', 'lglggllglglg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Śikhariṇī
-------------------------------------------------------------------------
lggggglllllgglllg    {m: 25}    [17: ymnsBlg]
lggggglllllggllll    {m: 24}    [17: ymnsBll]
lggggglllllgglllg    {m: 25}    [17: ymnsBlg]
lggggglllllgglllg    {m: 25}    [17: ymnsBlg]

   bha   vaḥ    śa   rvo    ru  draḥ    pa    śu    pa    ti    ra   tho  graḥ    sa    ha    ma   hāṃ
     l     g     g     g     g     g     l     l     l     l     l     g     g     l     l     l     g
   sta   thā   bhī    me    śā    nā    vi    ti    ya    da   bhi   dhā    nā   ṣṭa    ka    mi    da
     l     g     g     g     g     g     l     l     l     l     l     g     g     l     l     l     l
    ma    mu   ṣmi  npra   tye   kaṃ   pra    vi    ca    ra    ti    de    va   śru    ti    ra   pip
     l     g     g     g     g     g     l     l     l     l     l     g     g     l     l     l     g
    ri    yā    yā  smai   dhā   mne   pra    vi    hi    ta    na    ma   syo  'smi   bha    va    te
     l     g     g     g     g     g     l     l     l     l     l     g     g     l     l     l     g

śikhariṇī [17: ymnsBlg]

-------------------------------------------------------------------------
['lggggglllllgglllg', 'lggggglllllggllll', 'lggggglllllgglllg', 'lggggglllllgglllg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Śālinī
-------------------------------------------------------------------------
ggggglgglgg    {m: 20}    [11: mttgg]
ggggglgglgl    {m: 19}    [11: mttgl]
ggggglgglgg    {m: 20}    [11: mttgg]
ggggglgglgg    {m: 20}    [11: mttgg]

     ya    tra   bhrā   ntyā     ka    lpi    taṃ     ya    dvi     ve     ke
      g      g      g      g      g      l      g      g      l      g      g
     ta    tta    nmā   traṃ    nai     va     ta    smā    dvi    bhi    nna
      g      g      g      g      g      l      g      g      l      g      l
  mbhrā    nte    rnā     śe   bhrā    nti     dṛ    ṣṭā     hi     ta  ttvaṃ
      g      g      g      g      g      l      g      g      l      g      g
     ra    jju    sta    dva    dvi    śva     mā    tma    sva     rū    pam
      g      g      g      g      g      l      g      g      l      g      g

śālinī [11: mttgg]

-------------------------------------------------------------------------
['ggggglgglgg', 'ggggglgglgl', 'ggggglgglgg', 'ggggglgglgg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------
Śārdūlavikrīḍita
-------------------------------------------------------------------------
gggllglglllggglgglg    {m: 30}    [19: msjsttg]
gggllglglllggglgglg    {m: 30}    [19: msjsttg]
gggllglglllggglgglg    {m: 30}    [19: msjsttg]
gggllglglllggglgglg    {m: 30}    [19: msjsttg]

     mā    taḥ    kaḥ     pa     ri     va    rṇi    tuṃ     ta     va     gu    ṇaṃ     rū    paṃ     ca     vi    śvā    tma    kaṃ
      g      g      g      l      l      g      l      g      l      l      l      g      g      g      l      g      g      l      g
     śa    kto     de     vi     ja     ga   ttra     ye     ba     hu     gu    ṇai    rde     vo   'tha     vā     mā     nu    ṣaḥ
      g      g      g      l      l      g      l      g      l      l      l      g      g      g      l      g      g      l      g
     ta   tkiṃ    sva    lpa     ma     ti   rbra     vī     mi     ka     ru    ṇāṃ     kṛ    tvā    sva     kī    yai    rgu    ṇai
      g      g      g      l      l      g      l      g      l      l      l      g      g      g      l      g      g      l      g
    rno    māṃ     mo     ha     ya     mā     ya     yā     pa     ra     ma     yā     vi    śve     śi     tu  bhyaṃ     na    maḥ
      g      g      g      l      l      g      l      g      l      l      l      g      g      g      l      g      g      l      g

śārdūlavikrīḍita [19: msjsttg]

-------------------------------------------------------------------------
['gggllglglllggglgglg', 'gggllglglllggglgglg', 'gggllglglllggglgglg', 'gggllglglllggglgglg']
-------------------------------------------------------------------------
-------------------------------------------------------------------------

In [7]:
from skrutable.meter_identification import MeterIdentifier
import re
MI = MeterIdentifier()


import re

def extract_lg_pattern(verse, verbose=False):
    if verbose: print(verse)
    verse = MI.identify_meter(
            verse,
            from_scheme='DEV',
            resplit_option='resplit_lite'
        )
    
    summary = verse.summarize()
    if verbose: print(summary)

    patterns = re.findall(
        r'^([lg]+)\s+\{m:',
        summary,
        re.MULTILINE
    )[:4]

    return ''.join(patterns)

In [26]:
for i, r in tqdm(df.iterrows(), total=df.shape[0]):
    verse = r['sa']
    pattern = extract_lg_pattern(verse)
    
    if len(pattern) == r['syllable_count']:
        continue
    else:
        print(
            f"Error at row {i}. "
            f"Meter = {r['meter_cd']}. "
            f"Pattern length = {len(pattern)}, "
            f"Expected = {r['syllable_count']}. "
            f"Pattern = {pattern}"
        )

  5%|▌         | 1500/29183 [00:00<00:14, 1893.38it/s]

Error at row 1138. Meter = Anuṣṭubh. Pattern length = 9, Expected = 32. Pattern = gglgllglg

100%|██████████| 29183/29183 [00:15<00:00, 1847.20it/s]

In [27]:
r = df.iloc[1138]

print("Row index:", r.name)
print("Meter:", r['meter_cd'])
print("Syllable count:", r['syllable_count'])
print("SA:")
print(r['sa'])

Row index: 1138
Meter: Anuṣṭubh
Syllable count: 32
SA:
नानापुष्पफले वृक्षैः कृत्रिमैरुपशोभितः नानागुरुमळतोपेतः स्वादुकामफलप्रदः ॥

In [33]:
extract_lg_pattern("नानापुष्पफले वृक्षैः कृत्रिमैरुपशोभितः नानागुरुमळतोपेतः स्वादुकामफलप्रदः ॥", True)

नानापुष्पफले वृक्षैः कृत्रिमैरुपशोभितः नानागुरुमळतोपेतः स्वादुकामफलप्रदः ॥
 gggllggg    {m: 14}    [8: msgg]
 glgllglg    {m: 12}    [8: rslg]
 ggllllgg    {m: 12}    [8: tngg]
gglgllglg    {m: 14}    [9: tBr]

     nā     nā     pu    ṣpa    pha     le     vṛ  kṣaiḥ
      g      g      g      l      l      g      g      g
     kṛ    tri    mai     ru     pa     śo    bhi    taḥ
      g      l      g      l      l      g      l      g
     nā     nā     gu     ru     ma     ḻa     to     pe
      g      g      l      l      l      l      g      g
    taḥ    svā     du     kā     ma    pha     la    pra    daḥ
      g      g      l      g      l      l      g      l      g

anuṣṭubh (1,2: pathyā; 3,4: ?? adhikākṣarā)

'gglgllglg'

# Rule Checking

In [1]:
import json

with open("chanda_rules.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [2]:
data.keys()

dict_keys(['Vasantatilakā', 'Anuṣṭubh', 'Śārdūlavikrīḍita', 'Mālinī', 'Indravajrā', 'Śālinī', 'Vaṃśastha', 'Śikhariṇī', 'Upendravajrā', 'Sragdharā'])

In [16]:
df_one_per_meter

,sa,hi,skr_out,syllable_count,skr_meter,meter_cd,comments,prompt,split
5931,गीतं नृत्यं विचित्रं च वादित्रं विविधं तथा शिक...,राजन् ! मैं विराटनगरकी स्त्रियोंको गीत गाने वि...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,Anuṣṭubh,Anuṣṭubh,NaN,Objective:\n\nGenerate a sanskrit verse in Anu...,train
27114,श्रीकृष्ण गोविन्द हरे मुरारे हे नाथ नारायण वास...,हे जिले ! तू 'श्रीकृष्ण ! गोविन्द ! हरे ! मुरा...,indravajrā [11: ttjgg],44,Indravajrā,Indravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Ind...,train
27399,शिशिर किरणधारी शैलबालाविहारी भव जलनिधितारी योग...,"जो चन्द्रकलाको धारण किये हैं, पार्वती रमण हैं,...",mālinī [15: nnmyy],60,Mālinī,Mālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Māl...,train
639,सत्त्वोन्मेषात् कदाचित् खलु विषयरसे दोषबोधेऽपि...,भूमन् ! 'सत्त्वगुण के उद्रेक से कभीकभी विषयरस ...,sragdharā [21: mrBnyyy],84,Sragdharā,Sragdharā,NaN,Objective:\n\nGenerate a sanskrit verse in Sra...,train
3127,षडङ्गयोगान्न तु नैव शुद्धं मनोविनाशान्न तु नैव...,"षडंगयोगसे भी आत्मा शुद्ध नहीं होता, मनका नाश ह...",upendravajrā [11: jtjgg],44,Upendravajrā,Upendravajrā,NaN,Objective:\n\nGenerate a sanskrit verse in Upe...,train
20554,त्वां शीलरूपचरितैः परमप्रकृष्टसत्वेन साच्चिकतय...,"आसुरीप्रकृतिवाले मनुष्य आपके लोकोत्तर शील, रूप...",vasantatilakā [14: tBjjgg],56,Vasantatilakā,Vasantatilakā,NaN,Objective:\n\nGenerate a sanskrit verse in Vas...,train
25073,तवामृतस्यन्दिनि पादपङ्कजे निवेशितात्मा कथमन्यद...,जो पुरुष आपके अमृतवर्षी चरणकमलों में दत्तचित्त...,vaṃśastha [12: jtjr],48,Vaṃśastha,Vaṃśastha,NaN,Objective:\n\nGenerate a sanskrit verse in Vaṃ...,train
7698,कृपापारावारां तपनतनयां तापशमनीं मुरारिप्रेयस्क...,"जो कृपाकी समुद्र, सूर्यकुमारी, तापको शान्त करन...",śikhariṇī [17: ymnsBlg],68,Śikhariṇī,Śikhariṇī,NaN,Objective:\n\nGenerate a sanskrit verse in Śik...,val
5002,यत् ते पृष्टं तन्मया चोपदिष्टं याथातथ्यं तद्वि...,राजन्! तुमने जो पूछा था उसके उत्तरमें मैंने तु...,śālinī [11: mttgg],44,Śālinī,Śālinī,NaN,Objective:\n\nGenerate a sanskrit verse in Śāl...,val
13229,रे रे चातक सावधानमनसा मित्र क्षणं श्रूयतामम्मो...,अरे मित्र पपीहे ! सावधानमनसे जरा एक क्षण सुन त...,śārdūlavikrīḍita [19: msjsttg],76,Śārdūlavikrīḍita,Śārdūlavikrīḍita,NaN,Objective:\n\nGenerate a sanskrit verse in Śār...,train

<bound method IndexOpsMixin.item of 20554    त्वां शीलरूपचरितैः परमप्रकृष्टसत्वेन साच्चिकतय...
Name: sa, dtype: str>

In [20]:
extract_lg_pattern(df_one_per_meter[df_one_per_meter['meter_cd']=='Vasantatilakā']['sa'].item(), verbose=True)

त्वां शीलरूपचरितैः परमप्रकृष्टसत्वेन साच्चिकतया प्रबलैश्च शास्त्रैः प्रख्यातदैवपरमार्थविदां मतैश्चनैवासुरप्रकृतयः प्रभवन्ति बोद्धुम् ॥
gglglllgllglgl    {m: 20}    [14: tBjjgl]
gglglllgllglgg    {m: 21}    [14: tBjjgg]
gglglllgllglgl    {m: 20}    [14: tBjjgl]
gglglllgllglgg    {m: 21}    [14: tBjjgg]

    tvāṃ      śī      la      rū      pa      ca      ri    taiḥ      pa      ra      ma     pra      kṛ     ṣṭa
       g       g       l       g       l       l       l       g       l       l       g       l       g       l
      sa     tve      na      sā     cci      ka      ta      yā     pra      ba     lai     śca      śā  straiḥ
       g       g       l       g       l       l       l       g       l       l       g       l       g       g
     pra    khyā      ta     dai      va      pa      ra      mā    rtha      vi     dāṃ      ma     tai     śca
       g       g       l       g       l       l       l       g       l       l       g       l       g       l
     nai      vā      su      ra     pra      kṛ      ta     yaḥ     pra     bha      va     nti      bo   ddhum
       g       g       l       g       l       l       l       g       l       l       g       l       g       g

vasantatilakā [14: tBjjgg]

'gglglllgllglglgglglllgllglgggglglllgllglglgglglllgllglgg'

In [5]:
for k, v in data.items():
    print(f"METER: {k}")
    print(f"RULES: {v}")
    print("----------------------------------------------------")

METER: Vasantatilakā
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 56 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 14 syllables.
The pattern of syllables in every pāda must be: तगण (GGL), भगण (GLL), जगण (LGL), जगण (LGL), followed by two Guru (GG) syllables.
The complete pattern for each pāda is: GGL GLL LGL LGL GG.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Anuṣṭubh
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

The goal is to generate Sanskrit verse that follows the anushtup meter rules for the given input translation.
RULES:
Verse Rules:
The verse contains 32 syllables/akshara and 4 padas in total.
The verse is divided in 2 lines, each containing 16 syllables.
Each line is divided into 2 padas (quartets),each containing exactly 8 syllables.
The fifth syllable of every pada must be LAGHU or short.
The sixth syllable of every pada must be GURU or long.
The seventh syllable of the second and the fourth pada must be HRASVA
The seventh syllable of the first and third paada must be DEERGHA
----------------------------------------------------
METER: Śārdūlavikrīḍita
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 76 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 19 syllables.
The pattern of syllables in every pāda must be: मगण (GGG), सगण (LLG), जगण (LGL), सगण (LLG), तगण (GGL), तगण (GGL), followed by a Guru (G). A caesura (yati) occurs after the 12th syllable.
The complete pattern for each pāda is: GGG LLG LGL LLG GGL GGL G.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Mālinī
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 60 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 15 syllables.
The pattern of syllables in every pāda must be: नगण (LLL), नगण (LLL), मगण (GGG), यगण (LGG), followed by यगण (LGG). A caesura (yati) occurs after the 8th syllable.
The complete pattern for each pāda is: LLL LLL GGG LGG LGG.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Indravajrā
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 44 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 11 syllables.
The pattern of syllables in every pāda must be: तगण (GGL), तगण (GGL), जगण (LGL), followed by two Guru (GG) syllables.
The complete pattern for each pāda is: GGL GGL LGL GG.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Śālinī
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 44 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 11 syllables.
The pattern of syllables in every pāda must be: मगण (GGG), तगण (GGL), तगण (GGL), followed by two Guru (GG) syllables. A caesura (yati) occurs after the 4th syllable.
The complete pattern for each pāda is: GGG GGL GGL GG.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Vaṃśastha
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 48 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 12 syllables.
The pattern of syllables in every pāda must be: जगण (LGL), तगण (GGL), जगण (LGL), followed by रगण (GLG).
The complete pattern for each pāda is: LGL GGL LGL GLG.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Śikhariṇī
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 68 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 17 syllables.
The pattern of syllables in every pāda must be: यगण (LGG), मगण (GGG), नगण (LLL), सगण (LLG), भगण (GLL), followed by a Laghu (L) and a Guru (G). A caesura (yati) occurs after the 6th syllable.
The complete pattern for each pāda is: LGG GGG LLL LLG GLL LG.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Upendravajrā
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 44 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 11 syllables.
The pattern of syllables in every pāda must be: जगण (LGL), तगण (GGL), जगण (LGL), followed by two Guru (GG) syllables.
The complete pattern for each pāda is: LGL GGL LGL GG.
L means Laghu, G means Guru.
----------------------------------------------------
METER: Sragdharā
RULES: Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
Syllable is marked laghu, guru and hrasva, deergha based on the vowel it contains.
Syllable containing anusvāra("ं") or visarga("ः") is always marked as guru.
Syllable that is followed by a conjunct consonant (saṁyuktākṣara)
is always marked guru.

Verse Rules:
The verse contains 84 syllables (akṣaras) and 4 pādas (lines) in total, with each pāda containing 21 syllables.
The pattern of syllables in every pāda must be: मगण (GGG), रगण (GLG), भगण (GLL), नगण (LLL), followed by three यगण (LGG LGG LGG). A caesura (yati) occurs at every 7th syllable.
The complete pattern for each pāda is: GGG GLG GLL LLL LGG LGG LGG.
L means Laghu, G means Guru.
----------------------------------------------------